name: Build and push Docker image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

        # Docker配置多平台环境
    - name: Set up Docker BuildX
      uses: docker/setup-buildx-action@v2 

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./
        platforms: |
          linux/386
          linux/amd64
          linux/arm/v5
          linux/arm/v7
          linux/arm64
        push: true
        tags: h55205l/con