name: Build and push Docker image

on:
  push:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [14]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
      
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Npm Install
      run: |
        npm install 
        npm install sqlite3 --build-from-source

    - name: Build Release
      run: pkg .

    - name: release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: "dist/**"
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
