name: Build and push Docker image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: Dockerfile
        push: false
        tags: h55205l/con:latest
    
    - name: Build Docker arm image
      uses: docker/build-push-action@v2
      with:
          context: ./
          file: Dockerfile-linux-arm
          push: false
          tags: h55205l/con:arm

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./
        push: true
        tags: h55205l/con:latest
    
    - name: Push Docker image
      uses: docker/build-push-action@v2
      with:
          context: ./
          push: true
          tags: h55205l/con:arm
