name: Build and push Docker image

on:
  push:
    branches: [ main ]
    tags:
        - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2


    - name: Extract tag name
      id: tag_name
      run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: Dockerfile
        push: false
        tags: h55205l/con:latest,h55205l/con:${{ env.TAG }}


    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./
        push: true
        tags: h55205l/con:latest,h55205l/con:${{ env.TAG }}

