name: Build and push Docker image

on:
  push:
    branches: [ main ]
    tags:
        - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy Sqllite Binding
      id: copy_file
      run: |
        echo $PWD
        ls
        mkdir -p ./node_modules/sqlite3/lib/binding/
        cp -r ./package/sqlite3/* ./node_modules/sqlite3/lib/binding/
        ls ./node_modules/sqlite3/lib/binding/

    - name: Npm Install
      run: |
        npm install 
        npm install sqlite3 --build-from-source

    - name: Build Release
      run: npm run pkg
    # step7: create release
    - name: release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: "dist/**"
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
