name: Build and push Docker image

on:
  push:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        architecture: [x64, arm64]
        node-version: [14]

    runs-on: ${{ matrix.os }}
    permissions: write-all

    steps:

    - name: Package into node binary
      uses: lando/pkg-action@v2
      with:
        entrypoint: bin/cli
        arch: ${{ matrix.arch }}
        node-version: ${{ matrix.node-version }}
        os: ${{ matrix.os }}

    - name: release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: "dist/**"
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
